---
- name: install dependencies
  # XXX Determine what RH repository this will belong to so that it can be
  # properly checked and errored if the repository is not enabled.
  package:
    name: rbd-mirror
    state: present
  tags:
    - package-install

- name: copy rbd-mirror bootstrap key
  copy:
    src: "{{ fetch_directory }}/{{ fsid }}{{ item.name }}"
    dest: "{{ item.name }}"
    owner: "ceph"
    group: "ceph"
    mode: "0600"
  with_items:
    - { name: "/var/lib/ceph/bootstrap-rbd-mirror/{{ cluster }}.keyring", copy_key: true }
    - { name: "/etc/ceph/{{ cluster }}.client.admin.keyring", copy_key: "{{ copy_admin_key }}" }
  when:
    - cephx
    - item.copy_key|bool

- name: create rbd-mirror keyring
  command: ceph --cluster {{ cluster }} --name client.bootstrap-rbd-mirror --keyring /var/lib/ceph/bootstrap-rbd-mirror/{{ cluster }}.keyring auth get-or-create client.rbd-mirror.{{ ansible_hostname }} osd 'allow rwx' mon 'allow r' -o /etc/ceph/{{ cluster }}.client.rbd-mirror.{{ ansible_hostname }}.keyring
  args:
    creates: /etc/ceph/{{ cluster }}.client.rbd-mirror.{{ ansible_hostname }}/keyring
  changed_when: false
  when: cephx

- name: set rbd-mirror key permissions
  file:
    path: /etc/ceph/{{ cluster }}.client.rbd-mirror.{{ ansible_hostname }}/keyring
    owner: "ceph"
    group: "ceph"
    mode: "0600"
  when: cephx

