---
- name: stop and remove the generic rbd-mirror service instance
  service:
      name: "ceph-rbd-mirror@{{ ceph_rbd_mirror_local_user }}"
      status: stopped
      enabled: no
  changed_when: false

- name: start and add the rbd-mirror service instance
  service:
      name: "ceph-rbd-mirror@rbd-mirror.{{ ansible_hostname }}"
      state: started
      enabled: yes
  changed_when: false
